### PR TITLE
Added SASL PLAIN Support & Updated Dockerfile

### PR DESCRIPTION
**Pull request by AtakanColak**
As per #161

### CODE REVIEW

**Comment by AtakanColak** [comment]
@thrawn01 @horkhe could you review please?

**Comment by AtakanColak** [comment]
@obukhov-sergey could anyone with write access review this PR please? I'm planning to clean my forks.

**Review by horkhe — APPROVED** [review]

**Comment by horkhe** [comment]
Looks good to me. @thrawn01 @MattDietz what do you think?

**Review by MattDietz — APPROVED** [review]

**Comment by AtakanColak** [comment]
Thank you for your approval, any plans on merge?

**Pull request merged**
